using System.Text.Json;

namespace OmegaAssetStudio.Calligraphy;

// Loads the precomputed skill animation manifest produced by the
// CharacterInspector dev tool's BuildSkillAnimManifest command. The manifest
// enumerates every animation segment of every power prototype across the
// game's Calligraphy.sip (Player / Teamup / Boss / NPC / Mob / Defaultattack
// / Rogue), in playback-order. The Animation Preview Skills panel consults
// this manifest BEFORE falling back to the 3-slot start/loop/end resolver —
// that way long skills (charge_start, charge_loop, charge_release, recover,
// swing01-03, etc.) play their full segment list instead of being truncated
// to three slots.
//
// The manifest is NOT bundled with the source — it contains per-power data
// derived from the user's game install (character names, power prototype
// paths, etc.). The loader searches in this order:
//   1) %LocalAppData%\OmegaAssetStudio\skill_animation_manifest.json
//      — generated by the user running the dev-tool regen step
//   2) <exe-dir>\Assets\skill_animation_manifest.json
//      — only present in dev builds that ship a sample
// If neither file is found, TryGetSegments returns null and the Animation
// Preview falls back to its 3-slot resolver. The feature gracefully degrades.
public static class SkillAnimationManifest
{
    private static readonly object _gate = new();
    private static bool _loaded;
    private static Dictionary<string, IReadOnlyList<SkillAnimationSegment>>? _byPowerName;

    public static int PowerCount
    {
        get { EnsureLoaded(); return _byPowerName?.Count ?? 0; }
    }

    // Returns the ordered list of segments for the given power, or null if
    // the manifest has no entry. Lookup is case-insensitive on powerName.
    public static IReadOnlyList<SkillAnimationSegment>? TryGetSegments(string powerName)
    {
        if (string.IsNullOrWhiteSpace(powerName)) return null;
        EnsureLoaded();
        if (_byPowerName is null) return null;
        return _byPowerName.TryGetValue(powerName, out var list) ? list : null;
    }

    private static void EnsureLoaded()
    {
        if (_loaded) return;
        lock (_gate)
        {
            if (_loaded) return;
            _loaded = true;
            try
            {
                string? path = ResolveManifestPath();
                if (path is null) return;
                using FileStream fs = File.OpenRead(path);
                using var doc = JsonDocument.Parse(fs);
                if (!doc.RootElement.TryGetProperty("powers", out var pArr) ||
                    pArr.ValueKind != JsonValueKind.Array) return;

                var byName = new Dictionary<string, IReadOnlyList<SkillAnimationSegment>>(StringComparer.OrdinalIgnoreCase);
                foreach (var el in pArr.EnumerateArray())
                {
                    string powerName = el.TryGetProperty("powerName", out var n) ? (n.GetString() ?? string.Empty) : string.Empty;
                    if (powerName.Length == 0) continue;
                    if (!el.TryGetProperty("animations", out var animArr) || animArr.ValueKind != JsonValueKind.Array) continue;
                    var list = new List<SkillAnimationSegment>();
                    foreach (var s in animArr.EnumerateArray())
                    {
                        list.Add(new SkillAnimationSegment
                        {
                            FieldName = s.TryGetProperty("fieldName", out var v1) ? v1.GetString() ?? string.Empty : string.Empty,
                            CalligraphyPath = s.TryGetProperty("calligraphyPath", out var v2) ? v2.GetString() : null,
                            SequenceName = s.TryGetProperty("sequenceName", out var v3) ? v3.GetString() ?? string.Empty : string.Empty,
                            Role = s.TryGetProperty("role", out var v4) ? v4.GetString() ?? string.Empty : string.Empty,
                            HostUpk = s.TryGetProperty("hostUpk", out var v5) ? v5.GetString() : null,
                            AnimSetObjectPath = s.TryGetProperty("animSetObjectPath", out var v6) ? v6.GetString() : null,
                            ResolutionStatus = s.TryGetProperty("resolutionStatus", out var v7) ? v7.GetString() ?? "OK" : "OK",
                        });
                    }
                    if (list.Count > 0)
                        byName[powerName] = list;
                }
                _byPowerName = byName;
            }
            catch
            {
                // Swallow — the runtime falls back to the 3-slot resolver if
                // the manifest can't be loaded.
            }
        }
    }

    // Resolution order:
    //   1) %LocalAppData%\OmegaAssetStudio\skill_animation_manifest.json
    //   2) <exe-dir>\Assets\skill_animation_manifest.json (legacy / dev)
    private static string? ResolveManifestPath()
    {
        string userPath = Path.Combine(
            Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),
            "OmegaAssetStudio",
            "skill_animation_manifest.json");
        if (File.Exists(userPath)) return userPath;

        string assetPath = Path.Combine(AppContext.BaseDirectory, "Assets", "skill_animation_manifest.json");
        if (File.Exists(assetPath)) return assetPath;

        return null;
    }
}

public sealed class SkillAnimationSegment
{
    public string FieldName { get; init; } = string.Empty;
    public string? CalligraphyPath { get; init; }
    public string SequenceName { get; init; } = string.Empty;
    public string Role { get; init; } = string.Empty;
    public string? HostUpk { get; init; }
    public string? AnimSetObjectPath { get; init; }
    public string ResolutionStatus { get; init; } = "OK";
}
